= Forvaltning av målarkitekturen
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-forvaltning:
endif::[]
:toc: left
:toclevels: 4
:sectnums:
:sectnumlevels: 9

Tekst forvaltning av målarkitekturen

#Tekst om overgangen fra kapabilitetene og løsningene beskrevet
over til informasjonsforvaltning og definisjon av datasett.#

Sektoren er i ferd med å bygge en distribuert arkitektur som benytter
løsere koblet, delte datakilder som inneholder data om sentrale
entiteter i sektoren som for eksempel studenter, ansatte,
forskningsprosjekt, forskningsresultater, læringsobjekter, med flere.
Disse kildene blir rendyrket som *_masterdatakilder_*. Disse kildene er
definert ut fra en dyp forståelse av sektorenes funksjon og vil typisk
være forholdsvis stabile over tid. Definisjon av …[mer tekst her]

:leveloffset: +1
include::main@unit-ra:unit-ra-datadeling-forvaltning:page$Utvikling av brukernære API og datasett.adoc[]
include::main@unit-ra:unit-ra-datadeling-forvaltning:page$Roller og ansvar for informasjonsforvaltning.adoc[]
:leveloffset: -1
