= Introduksjon
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-introduksjon:
endif::[]
:toc: left
:toclevels: 4
:sectnums:
:sectnumlevels: 9

Økt deling av data er en forutsetning for å realisere flere av
handlingsplanens initiativer innenfor utdanning, forskning,
administrasjon og IMD. Dette dokumentet beskriver de føringene til
organisasjoner og IT-løsninger som vi ønsker å bruke videre i sektoren
til å skape en effektiv plattform for datadeling. Referansearkitekturen
tar utgangspunkt i følgende pågående arbeid i sektoren i dag:

* Integrasjonsarkitektur UH:IntArk
* Arbeid med Sak og Arkiv i sektoren
* Arbeid med nytt API for Felles Studentsystem, FS
* Arbeid med masterdatakilder for forskning

Referansearkitekturen innarbeider også føringer fra:

* Digitaliseringsstrategiene til offentlig sektor og høyere utdanning og
forskning
* https://www.digdir.no/digitalisering-og-samordning/overordnede-arkitekturprinsipper/1065[Overordnede
arkitekturprinsipper] for digitaliering av offentlig sektor
* https://www.digdir.no/nasjonal-arkitektur/rammeverk-digital-samhandling/2148[Rammeverk
for digital samhandling]
* https://nasjonal-arkitektur.github.io/architecture-repository/about-topic-areas/about-topic-areas.html[Nasjonal
referansearkitekturene for datadeling og datautveksling]
* https://app.powerbi.com/view?r=eyJrIjoiMThhNjkzNmItOGQ4NC00MDkzLWI3MDQtNzY0ZjA1MjQ5MzViIiwidCI6ImFlMWE3NzI0LTQwNDEtNDQ2Mi1hNmRjLTUzOGNiMTk5NzA3ZSIsImMiOjh9[Kapabilitetsmodell
i høyere utdanning i EUNIS] (European University Information System
Organization)
* Behovene avdekket i tjenestedesign analyse av behovene til Studenter,
Lærere, Forskere og tjenesteleverandører av Muliggjørende økosystem

Referansearkitekturer gir mønstre og veiledning til utforming av
løsninger. Denne referansearkitekturen beskriver både eksisterende
samhandling formulert som beste praksis og nødvendig neste steg i
generelle datadelingsmønster som kan gjenbrukes i sektoren. Disse
mønstrene er dokumentert gjennom videreutvikling av
referansearkitekturene fra digitaliseringsdirektoratet. Hensikten med
arbeidet er å fremme en koordinert utvikling av datadeling som
resulterer i økt gjenbruk av data «kun en gang» og nye, innovative
anvendelser av data i sektoren.

Noe om prosesser, rutiner og veiledninger.

Noe om forvaltning av rammeverket

:leveloffset: +1
include::main@unit-ra:unit-ra-datadeling-introduksjon:page$Bakgrunn.adoc[]
include::main@unit-ra:unit-ra-datadeling-introduksjon:page$Forankring.adoc[]
include::main@unit-ra:unit-ra-datadeling-introduksjon:page$Målgruppe.adoc[]
:leveloffset: -1
