= Muliggjørende kapabiliteter (copy)
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-tilnærming:
endif::[]
:toc: left
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 9

For å være i stand til å utføre stegene i prosessen over, må
organisasjoner opparbeide evner, kalt «kapabiliteter». Noen
kapabiliteter er knyttet til bestemte steg i verdistrømmen over. Andre
kapabiliteter er generelle og «muliggjørende» for alle steg i
verdistrømmen.

God informasjonsforvaltning støtter både opp om organisatorisk
samhandlingsevne gjennom å gi organisasjoner riktig data av god kvalitet
og støtter opp om semantisk samhandlingsevne ved å klargjøre dataenes
betydning.

Vi velger også å synliggjøre juridiske tjenester som muliggjørende
kapabilitet for å støtte opp under juridisk samhandlingsevne. Alt i alt
krever digital samhandling kapabiliteter som er tverrfaglige, der ingen
kan fungere uten de andre.

.Muliggjørende kapabiliteter (copy)
image::{imagepath}Muliggjørende kapabiliteter (copy).png[alt=Muliggjørende kapabiliteter (copy) image]


****
xref:main@unit-ra:unit-ra-datadeling-tilnærming:page$Muliggjørende kapabiliteter (copy).var.1.adoc[Vis detaljer om elementene i diagrammet] (Tips: kbd:[Shift]-klikk for å åpne i nytt vindu)
****


