= Issues mot nasjonale felleskompontenter (Maskinporten, ID Porten og Altinn autorisasjon)
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-vedlegg-b:
endif::[]
:toc: left
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 9


[arabic]
. Harmonisering av autorisasjon
[loweralpha]
.. Det er ønskelig at UHF autorisasjonstjener og Maskinporten godkjenner
hverandres tilgangstokens. Dette forutsetter at informasjonsmodellen benyttet i
tokens er felles. Løsningsvarianter:
[lowerroman]
... Klienter forholder seg til flere autentiseringstjenere og
tjenestetilbyderne standardiserer token strukturen
... Innbytte av tokens (token exchange) fra andre “trusted”
autorisasjonstjenere. En konsekvens av dette er at man mister (?)
koblingen til bruker og dermed kjennskap til autentiseringsstyrken som
ligger bak.
... Software Statement Assertion (https://tools.ietf.org/html/rfc7521 –
løsning benyttet av Open Banking UK
. Harmonisering av samtykke
[loweralpha]
.. Altinn autorisasjon benytter «Self-contained OAuth2 token» for
samtykke. Men da vi ikke kan godkjenne tokens på tvers, har vi
utfordringer med å benytte Altinn autorisasjon direkte. I hvert fall
dekker ikke tjenesten «scopes» vi har anvar for i UHF autorisasjonstjeneren.
.. Kan «User Managed Access (UMA)» være et alternativ her?
. Delegering av authorisasjons-rettigheter: Altinn har per i dag ingen god
mekanisme for å delegere rettigheter under organisasjonsgranulariteten i
Enhetsregisteret. UHF sektorene arbeider med mekanismer for authorisasjon og tilgangsstyring i sektorene våre. Det er ønskelig med en helhetlig nasjonal modell for authorisasjon og tilgangsstyring som fungerer på tvers av sektorer.


