= Vedlegg E; Føringer, pågående og videre arbeid
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-vedlegg-e:
endif::[]
:toc: left
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 9

Dette dokumentet beskriver de føringene til organisasjoner og
IT-løsninger som vi ønsker å bruke videre i sektoren til å skape en
effektiv plattform for datadeling. Referansearkitekturen tar
utgangspunkt i følgende pågående arbeid i sektoren i dag:

* Datadeling - UH:IntArk
* Arbeid med Sak og Arkiv i sektoren
* Arbeid med nytt API for Felles Studentsystem, FS
* Arbeid med masterdatakilder for forskning

Referansearkitekturen innarbeider også føringer fra:

* Digitaliseringsstrategiene til offentlig sektor og høyere utdanning og
forskning
* https://www.digdir.no/digitalisering-og-samordning/overordnede-arkitekturprinsipper/1065[Overordnede
arkitekturprinsipper] for digitalisering av offentlig sektor
* https://www.digdir.no/nasjonal-arkitektur/rammeverk-digital-samhandling/2148[Rammeverk
for digital samhandling]
* https://nasjonal-arkitektur.github.io/architecture-repository/about-topic-areas/about-topic-areas.html[Nasjonal
referansearkitekturene for datadeling og datautveksling]
* https://app.powerbi.com/view?r=eyJrIjoiMThhNjkzNmItOGQ4NC00MDkzLWI3MDQtNzY0ZjA1MjQ5MzViIiwidCI6ImFlMWE3NzI0LTQwNDEtNDQ2Mi1hNmRjLTUzOGNiMTk5NzA3ZSIsImMiOjh9[Capability
model from EUNIS] (European University Information System Organization)
* Behovene avdekket i tjenestedesign analyse av behovene til Studenter,
Lærere, Forskere og tjenesteleverandører av et "Muliggjørende økosystem". 

En viktig forutsetning for videre arbeid med samhandling og datadeling
er Digitaliseringsdirektoratets
https://data.norge.no/guide/veileder-orden-i-eget-hus/[«Orden i eget
hus»]:

____
_«Med orden i eget hus mener vi at “den enkelte virksomhet skal ha
oversikt over hvilke data den håndterer, hva dataene betyr, hva de
brukes til, hvilke prosesser de inngår i, og hvem som kan bruke dem
(informasjonsforvaltning)֦ . Dette innebærer også å ta stilling til
hvilke data som kan gjøres tilgjengelig for gjenbruk i offentlig sektor,
og viderebruk av privat sektor. Offentlige virksomheter må prioritere
utveksling av informasjon som andre virksomheter har krav
på https://www.regjeringen.no/no/dokumenter/digitaliseringsrundskrivet/id2895185/[(Digitaliseringsrundskrivet)].”_
____

Referansearkitekturen forutsetter at virksomheter i UHF-sektoren har
gjennomført eller er i gang med å gjennomføre prosesser for å skape
«orden i eget hus».

=== UH:IntArk-*prosjektet*

UH:IntArk-prosjektet som tidligere er gjennomført i regi av UH-IT har
utarbeidet et forslag til referansearkitektur for integrasjon. Denne er
testet ut med en proof-of-concept. Dette proof-of-concept er
videreutviklet i Datadelingsprosjektet for leveranse til hele UH
sektoren som UH: IntArk fase 1.

Referansearkitekturen beskrevet i dette dokumentet er et målbilde for
neste fase, som vi her kaller UH:IntArk fase 2. Mange element i
målbildet kan med fordel rulles ut så tidlig som mulig, for eksempel
tiltak rettet mot orden i eget hus.

=== Dette notatet og videre

Arbeidsgrupper i datadelingsprosjektet har samarbeidet i utformingen av
referansearkitekturen for deling av data i høyere utdanning og forskning
(UHF). Denne referansearkitekturen vil danne grunnlag for
videreutvikling av UH:IntArk i fase 2. Arbeidsgruppen har i sitt arbeid
tatt utgangspunkt i den nasjonale https://www.digdir.no/datadeling/nasjonal-verktoykasse-deling-av-data/2243[Verktøykassen for deling av data] samt https://nasjonal-arkitektur.github.io/architecture-repository/data-exchange-ra/book-data-exchange-ra.html[Referansearkitektur for datautveksling] og tilpasset
denne til UHF.

Den anbefalte referansearkitekturen er beskrevet i dette notatet.

Deler av referansearkitekturen beskrevet her vil inngå i
referansearkitekturen for Kunnskapssektorens datafellesskap (en
infrastruktur for deling av data til sekundær- og viderebruk fra hele
KDs sektor), og arbeidet er koordinert med dette tiltaket som er i
skrivende stund i en forprosjektfase.

Referansearkitekturer gir mønstre og veiledning til utforming av
løsninger. Denne referansearkitekturen beskriver både eksisterende
samhandling formulert som beste praksis og nødvendig neste steg i
generelle datadelingsmønster som kan gjenbrukes i sektoren. Disse
mønstrene er dokumentert gjennom videreutvikling av
referansearkitekturene fra digitaliseringsdirektoratet. Hensikten med
arbeidet er å fremme en koordinert utvikling av informasjonsforvaltning
og datadeling som resulterer i «orden i eget hus», økt gjenbruk av data
«kun en gang» og nye, innovative anvendelser av data i sektoren.

Vi forventer at referansearkitekturen vil videreutvikles over tid. Vi
mener at innholdet som finnes nå har tilstrekkelig veiledning til å føre
til gevinst, samtidig er vi klar over mangler som vi ønsker skal være
dekket så snart som praktisk mulig:

* Rutinen for utvikling av indre API burde være detaljert
* Retningslinjer for spesifikasjon av API burde vært definert. Vi tenker
å benytte Open API spesifikasjon som en del av retningslinjene for REST
APIene. GraphQL vurderes i tillegg.
* Prosesser for rettighetsklarering av dataprodukter bør defineres
* Føringer til beskrivelser av dataprodukter bør defineres. Det er et
mål at dataprodukter skal være mest mulig selvbeskrivende.
* Begrepsdefinisjoner bør suppleres og publiseres i begrepskatalogen
* Notifikasjoner som er realisert ved bruk av hendelseslister vurderes
ut fra behov
* Bearbeide IntArk arkitekturprinsipper og annen kildemateriale for å konkretisere føringer fra  https://www.digdir.no/digitalisering-og-samordning/overordnede-arkitekturprinsipper/1065[Overordnede
arkitekturprinsipper] og https://www.go-fair.org/fair-principles/["FAIR Guiding Principles for scientific data management and stewardship"] for deling av data.



:leveloffset: +1
include::main@unit-ra:unit-ra-datadeling-vedlegg-e:page$Om arkitekturprinsippenes føringer for datadeling.adoc[]
:leveloffset: -1
