= Vedlegg E; Føringer
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-vedlegg-e:
endif::[]
:toc: left
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 9

Dette dokumentet beskriver de føringene til organisasjoner og
IT-løsninger som vi ønsker å bruke videre i sektoren til å skape en
effektiv plattform for datadeling. Referansearkitekturen tar
utgangspunkt i følgende pågående arbeid i sektoren i dag:

* Datadeling - UH:IntArk
* Arbeid med Sak og Arkiv i sektoren
* Arbeid med nytt API for Felles Studentsystem, FS
* Arbeid med masterdatakilder for forskning

Referansearkitekturen innarbeider også føringer fra:

* Digitaliseringsstrategiene til offentlig sektor og høyere utdanning og
forskning
* https://www.digdir.no/digitalisering-og-samordning/overordnede-arkitekturprinsipper/1065[Overordnede
arkitekturprinsipper] for digitalisering av offentlig sektor
* https://www.digdir.no/nasjonal-arkitektur/rammeverk-digital-samhandling/2148[Rammeverk
for digital samhandling]
* https://nasjonal-arkitektur.github.io/architecture-repository/about-topic-areas/about-topic-areas.html[Nasjonal
referansearkitekturene for datadeling og datautveksling]
* https://app.powerbi.com/view?r=eyJrIjoiMThhNjkzNmItOGQ4NC00MDkzLWI3MDQtNzY0ZjA1MjQ5MzViIiwidCI6ImFlMWE3NzI0LTQwNDEtNDQ2Mi1hNmRjLTUzOGNiMTk5NzA3ZSIsImMiOjh9[Capability
model from EUNIS] (European University Information System Organization), for tiden under endring, basert på HERM (Higher Education Reference Model, basert på CAUDIT, UCISA, EDUCAUSE og EUNIS) kapabilitetsmodell
* Behovene avdekket i tjenestedesign analyse av behovene til Studenter,
Lærere, Forskere og tjenesteleverandører av et "Muliggjørende økosystem". 

En viktig forutsetning for videre arbeid med samhandling og datadeling
er Digitaliseringsdirektoratets
https://data.norge.no/guide/veileder-orden-i-eget-hus/[«Orden i eget
hus»]:

____
_«Med orden i eget hus mener vi at “den enkelte virksomhet skal ha
oversikt over hvilke data den håndterer, hva dataene betyr, hva de
brukes til, hvilke prosesser de inngår i, og hvem som kan bruke dem
(informasjonsforvaltning)֦ . Dette innebærer også å ta stilling til
hvilke data som kan gjøres tilgjengelig for gjenbruk i offentlig sektor,
og viderebruk av privat sektor. Offentlige virksomheter må prioritere
utveksling av informasjon som andre virksomheter har krav
på https://www.regjeringen.no/no/dokumenter/digitaliseringsrundskrivet/id2895185/[(Digitaliseringsrundskrivet)].”_
____

Referansearkitekturen forutsetter at virksomheter i UHF-sektoren har
gjennomført eller er i gang med å gjennomføre prosesser for å skape
«orden i eget hus».


