= Datadeling på tvers av sektorer
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-målarkitekturen:
endif::[]
:toc: left
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 9

Det er behov for datadeling og API Management på tvers av sektorer.
Høyere utdanning og forskning ønsker utstrakt bruk av nasjonale
felleskomponenter, som omtalt i Digitaliseringsrundskrivet og vist i
figuren over. For å oppnå dette må både sektorens og den nasjonale
infrastrukturen videreutvikles.​

Føderert tilgangsstyring for datadeling på tvers av sektorer er
ønskelig, og det krever blant annet standardisering av
sikkerhetsbilletter (tokens) for å oppnå gjennomgående tillitskjeder.
​Det er også ønskelig at brukere kan styre samtykke til sine data fra
_et_ sted nasjonalt, inklusivt til data i kilder i høyere utdanning og
forskning. Det hadde vært ønskelig om en felles Norsk samtykketjeneste
kunne være integrert med funksjonalitet som vi forvente skal realiseres
i IAM løsningen til høyere utdanning og forskning. Samtykke til kilder i
vår sektor fra Altinn autorisasjon er en mulig fremtidig løsning.

Det er planlagt automatisert høsting av API katalogen fra høyere
utdanning og forskning til Felles API-katalog som visst i figuren under.

