= Datadelingsplattformen og felles komponentene i den
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-målarkitekturen:
endif::[]
:toc: left
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 9

Datadeling i og mellom domener i økosystemet skjer ved bruk av
datadelingsplattformen i høyere utdanning og forskning.
Datadelingplattformen består av felleskomponentene og bruk av disse for
å realisere datautvekslingsmønstrene beskrevet i referansearkitekturen.

Saksbehandling og daglig drift hos institusjonene skjer ofte i kjernen
av virksomheten, i det vi kaller de grunnleggende domener, mens arbeid i
læringsgrupper og forskningsprosjekt skjer i brukersentriske domener.

I praksis betyr dette samhandling i høyere utdanning og forskning.
Samhandlingen kan skje mellom medlemmer i lærings- og forskningsgrupper
både innenfor egne institusjoner og på tvers av institusjoner. Andre
områder for samhandling kan være innen saksbehandling og annen
administrasjon innen en institusjon, eller mellom institusjonene og
andre sektorer i inn- og utland.

Plattformen skal støtte enkel publisering av data og effektive
mekanismer for gjenfinning og tilgang til data for konsumenter som har
rett til slik tilgang. Referansearkitekturen definerer prosessene og
IT-støttede samhandlingsmønstre for å realisere deling av data.

Referansearkitekturen spesifiserer hvordan *datasett og API* skal:

* defineres
* brukes
* gjenbrukes av nye konsumenter
* brukes til nye oppgaver.

Datasett til nye formål kan være satt sammen av data fra flere andre
API. +
Deler av delingsplattformen skal inngå i Kunnskapsdepartementets
datafellesskap der det skal bygges et økosystem for bruk av data rundt
plattformen.

Virksomhetene i høyere utdanning og forskning må etablere tillit til
hverandre for å kunne dele data. Datadelingsplattformen realiserer
tilgangsstyring til sektorens data på en enhetlig måte gjennom bruk av
felleskomponenter i plattformen. Hovedmetoden for tilgangsstyring i
plattformen er API Management.

Referansearkitekturen definerer hvordan det varsles om endringer i
datasett gjennom notifikasjoner. Varslene brukes til å reagere på
endringene i datasettet, uten at hele datasettet konsumeres. Muligheten
til å reagere på varsler om endringer tilrettelegger for hurtig
behandling av data i situasjoner der tidsbruk er et sentralt kriterium
for bruksmønsteret.

:leveloffset: +1
include::main@unit-ra:unit-ra-datadeling-målarkitekturen:page$Føderert API management.adoc[]
include::main@unit-ra:unit-ra-datadeling-målarkitekturen:page$Publisering av hendelser.adoc[]
include::main@unit-ra:unit-ra-datadeling-målarkitekturen:page$Felleskomponenter.adoc[]
include::main@unit-ra:unit-ra-datadeling-målarkitekturen:page$Datadeling integrert med IAM.adoc[]
include::main@unit-ra:unit-ra-datadeling-målarkitekturen:page$Datadeling på tvers av sektorer.adoc[]
:leveloffset: -1
