= Integrasjonsmønster for datadeling
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-målarkitekturen:
endif::[]
:toc: left
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 9

Tekst integrasjonsmønster for datadeling

*Provisjonering *(hoved IntArk mønster): Holde «server-side» kopi løpende oppdatert
fra master ved å benytte eOppslag til å hente data fra master
og eNotifikasjon for å gi beskjed til abonnenter om at noe er
oppdatert på master. 

**Synkront oppslag: **realisering av eOppslag – hva bør vi si om
dette? Skal vi Skissere REST og GraphQL eller blir det for
teknologispesifikk?

**“Event stream” på logisk nivå: **Dette er en form
for ePublisering/eNotfikasjon. Ref. Gartner sin FS evaluering, men siden
de ikke har åpen dokumentasjon** **se for eksempel
denne:** **https://mapr.com/blog/event-driven-microservices-patterns/[[.underline]#https://mapr.com/blog/event-driven-microservices-patterns/#].
Overordnet, omtales arkitekturen som
“https://en.wikipedia.org/wiki/Event-driven_architecture[[.underline]#Event Driven
Architecture#]”.^2^  Tilnærmingen forutsetter tilnærming til konsistens
omtalt
som «https://en.wikipedia.org/wiki/Eventual_consistency[[.underline]#Eventual
Consistency#]». «Conflict resolution» kan her gjennomføres på flere
måter avhengig av domenebehov. Mange benytter «last writer wins», men
det finnes flere, strengere alternativer, som for
eksempel https://debezium.io/blog/2020/02/10/event-sourcing-vs-cdc/[[.underline]#Event
sourcing og Change Data Capture#]. 


*Backend for frontend*: relevant når vi skal spesifisere samhandling med
individer, som i innovativ læring og livslang læring. eHelse sier
«Backend-for-Frontend (BFF) er et utbredt designkonsept som benyttes for
mange klienter og API-er. Konseptet går ut på å la
ulike brukergrensesnittyper (Nettleserbaserte, App-er på mobil osv) ha
hver sin backend slik at spesialtilpasninger på API-er som kreves for de
ulike brukergrensesnitttypene kan realiseres uten at det går
utover vedlikeholdbarheten til API-ene.» Gartner bruker også den.  

