= Kapabiliteter
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@unit-ra:unit-ra-datadeling-målarkitekturen:
endif::[]
:toc: left
:toclevels: 4
:sectnums:
:sectnumlevels: 9

Som vist i #figuren over#, må datatilbyderen ha oversikt over egne data
som skal deles og evne til å publisere datasettene slik at andre kan
benytte disse. 

For at datadeling skal fungere etter hensikt, må dataene
ha god kvalitet. Dette krever kapabiliteter innen
informasjonsforvaltning.  Vi har modellert disse evner som
«muliggjørende kapabiliteter» i referansearkitekturen for høyere
utdanning og forskning med utgangspunkt i
https://app.powerbi.com/view?r=eyJrIjoiMThhNjkzNmItOGQ4NC00MDkzLWI3MDQtNzY0ZjA1MjQ5MzViIiwidCI6ImFlMWE3NzI0LTQwNDEtNDQ2Mi1hNmRjLTUzOGNiMTk5NzA3ZSIsImMiOjh9[EUNIS
sin kapabilitetsmodell for europeiske universiteter] #som vist under#. 


God
informasjonsforvaltning støtter både opp om organisatorisk
samhandlingsevne gjennom å gi organisasjoner riktig data av god kvalitet
og støtter opp om semantisk samhandlingsevne ved å klargjøre dataenes
betydning. Vi velger også å synliggjøre juridiske tjenester som
muliggjørende kapabilitet for å støtte opp under juridisk
samhandlingsevne.



:leveloffset: +1
include::main@unit-ra:unit-ra-datadeling-målarkitekturen:page$Innhent data, detaljert verdistrøm konsument med kapabiliteter.adoc[]
include::main@unit-ra:unit-ra-datadeling-målarkitekturen:page$Del og innhent data og hendelser, detaljert verdistrøm datatilbyder med kapabiliteter.adoc[]
include::main@unit-ra:unit-ra-datadeling-metode:page$Muliggjørende kapabiliteter.adoc[]
include::main@unit-ra:unit-ra-datadeling-metode:page$Informasjonsforvaltningsdomener.adoc[]
include::main@unit-ra:unit-ra-datadeling-metode:page$Domener.adoc[]
:leveloffset: -1
